# El bloque try no genera ning√∫n error:
try:
    print("Hola")
except:
    print("Algo salio mal")
else:
    print("Nada salio mal")
